name: Build and Deploy Pelican site to GitHub Pages

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Build:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install requirements
        run: pip install "pelican[markdown]"
      
      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v3
      
      - name: Print Pelican settings
        run: pelican --print-settings > .pelican_settings.json
      
      - name: Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('.pelican_settings.json') }}
          path: cache
      
      - name: Build Pelican site
        run: pelican --settings publishconf.py --extra-settings SITEURL='"${{ steps.pages.outputs.base_url }}"'
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: output

  Deploy:
    if: github.event.pull_request.merged == true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
